# 7-base_geometry.txt
# Carlos Barros <1543@holbertonschool.com>

===========================
How to Use 7-base_geometry.py
===========================

This module defines an function divides all elements of a matrix ``def integer_validator(self, name, value)``.

Usage
=====

``base_geometry(...)```  validates value
---------------------

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry


===============
Handle error 
================

    >>> bg = BaseGeometry()
    >>> print(bg.integer_validator("my_int", None))
    Traceback (most recent call last):
    TypeError: my_int must be an integer

    >>> bg = BaseGeometry()
    >>> print(type(bg))
    <class '7-base_geometry.BaseGeometry'>

    >>> bg = BaseGeometry()
    >>> print(bg.area())
    Traceback (most recent call last):
    Exception: area() is not implemented

    >>> bg = BaseGeometry()
    >>> print(bg.integer_validator(3))
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    >>> bg = BaseGeometry()
    >>> print(bg.integer_validator("my_int", -12))
    Traceback (most recent call last):
    ValueError: my_int must be greater than 0

    >>> bg = BaseGeometry()
    >>> print(bg.integer_validator("my_int", 1.2))
    Traceback (most recent call last):
    TypeError: my_int must be an integer
    
    >>> bg = BaseGeometry()
    >>> print(bg.integer_validator("my_int", "hello"))
    Traceback (most recent call last):
    TypeError: my_int must be an integer

    >>> bg = BaseGeometry()
    >>> print(bg.integer_validator())
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Both ``name`` and ``value`` must be provided. Otherwise, a TypeError is raised.

::

    >>> bg.integer_validator() # doctest: +NORMALIZE_WHITESPACE
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 
    'name' and 'value'

::

    >>> bg.integer_validator(None) # doctest: +NORMALIZE_WHITESPACE
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 
    'value'

The method assumes the paramter ``name`` will be a string, but ``name`` of any
type will be printed.

::

    >>> bg.integer_validator({"a": 1}, (1, 2))
    Traceback (most recent call last):
    TypeError: {'a': 1} must be an integer

But, if ``value`` is not an integer, a ``TypeError`` is raised.

::

    >>> bg.integer_validator("invalid number", "number")
    Traceback (most recent call last):
    TypeError: invalid number must be an integer

::

    >>> bg.integer_validator("invalid tuple", (1,))
    Traceback (most recent call last):
    TypeError: invalid tuple must be an integer

::

    >>> bg.integer_validator("and another", [3])
    Traceback (most recent call last):
    TypeError: and another must be an integer

::

    >>> bg.integer_validator("more invalid testing", {3, 4})
    Traceback (most recent call last):
    TypeError: more invalid testing must be an integer

::

    >>> bg.integer_validator("absolutely every possible invalid", None)
    Traceback (most recent call last):
    TypeError: absolutely every possible invalid must be an integer

And if ``value`` is an integer, but less than or equal to zero, a ValueError
is raised.

::

    >>> bg.integer_validator("invalid int", -1)
    Traceback (most recent call last):
    ValueError: invalid int must be greater than 0

::

    >>> bg.integer_validator("invalid int", 0)
    Traceback (most recent call last):
    ValueError: invalid int must be greater than 0



    ::

    >>> bg = BaseGeometry()
    >>> print(bg.area) # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
    <bound method BaseGeometry.area of <7-base_geometry.BaseGeometry 
     object at...>>

::

    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

The second method, ``integer_validator(...)``, validates the integer value
of a paramter. The first parameter, ``name``, is the name of the argument to
check. The second argument, ``value``, is the argument to check.

::

    >>> print(bg.integer_validator) # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
    <bound method BaseGeometry.integer_validator of <7-base_geometry.BaseGeometry 
    object at...>>

If ``value`` is a valid integer, the function does nothing.

::


   >>> bg.integer_validator("valid number", 1)

But, if ``value`` is not an integer, a ``TypeError`` is raised.

::

    >>> bg.integer_validator("invalid number", "number")
    Traceback (most recent call last):
    TypeError: invalid number must be an integer

::

    >>> bg.integer_validator("invalid tuple", (1,))
    Traceback (most recent call last):
    TypeError: invalid tuple must be an integer

::

>>> bg.integer_validator("and another", [3])
Traceback (most recent call last):
TypeError: and another must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("my_int", 7)
>>> bg.integer_validator("something", 12)
>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

>>> bg.integer_validator("name", "Monty")
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", [3])
Traceback (most recent call last):
...
TypeError: name must be an integer
>>> bg.integer_validator("name", {7,8})
Traceback (most recent call last):
...
TypeError: name must be an integer
>>> bg.integer_validator("name", (7, ))
Traceback (most recent call last):
...
TypeError: name must be an integer
>>> bg.integer_validator("name", None)
Traceback (most recent call last):
...
TypeError: name must be an integer
>>> bg.integer_validator("num", "3")
Traceback (most recent call last):
...
TypeError: num must be an integer
>>> bg.integer_validator("neg_num", -3)
Traceback (most recent call last):
...
ValueError: neg_num must be greater than 0

>>> bg.integer_validator("float", 7.3)
Traceback (most recent call last):
...
TypeError: float must be an integer

>>> bg.integer_validator("neg_float", -3.5)
Traceback (most recent call last):
...
TypeError: neg_float must be an integer



>>> bg.integer_validator("age")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'
>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented